spring:
  application:
    name: gcp-subscriber
  cloud:
    gcp:
      project-id: mythic-origin-471314-c6
      credentials:
        location: classpath:service-account-subscriber.json

server:
  port: 8081
